# Generated by Django 4.0.5 on 2022-07-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_alter_companyrole_require_cv_delete_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrole',
            name='require_CV',
        ),
        migrations.AddField(
            model_name='companyrole',
            name='addi_info',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
